name: secrets and variables
on: workflow_dispatch
jobs:
  secrets-variables:
    runs-on: ubuntu-latest
    steps:
      - name: calling variables
        run: echo " db username is ${{vars.DB_USER}}"
      - name: calling secrets
        run: echo " db name is ${{secrets.DB_NAME}} and port is ${{secrets.DB_PORT}}"
      - name: Use secret with mask
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "::add-mask::$DB_PASSWORD"
          echo "Connecting to DB..."
